(function(){CKEDITOR.plugins.add("codemirror",{icons:"searchcode,autoformat,commentselectedrange,uncommentselectedrange,autocomplete",lang:"af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en-au,en-ca,en-gb,en,eo,es,et,eu,fa,fi,fo,fr-ca,fr,gl,gu,he,hi,hr,hu,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt-br,pt,ro,ru,sk,sl,sr-latn,sr,sv,th,tr,ug,uk,vi,zh-cn,zh",version:1.13,init:function(b){function f(){var a=[d+"js/codemirror.addons.min.js"];switch(c.mode){case "bbcode":a.push(d+"js/codemirror.mode.bbcode.min.js");
break;case "bbcodemixed":a.push(d+"js/codemirror.mode.bbcodemixed.min.js");break;case "htmlmixed":a.push(d+"js/codemirror.mode.htmlmixed.min.js");break;case "text/html":a.push(d+"js/codemirror.mode.htmlmixed.min.js");break;case "application/x-httpd-php":a.push(d+"js/codemirror.mode.php.min.js");break;case "text/javascript":a.push(d+"js/codemirror.mode.javascript.min.js");break;default:a.push(d+"js/codemirror.mode.htmlmixed.min.js")}c.useBeautify&&a.push(d+"js/beautify.min.js");c.enableSearchTools&&
a.push(d+"js/codemirror.addons.search.min.js");return a}function h(a){function b(a){for(var c=[[CKEDITOR.SHIFT,"Shift-"],[CKEDITOR.CTRL,"Ctrl-"],[CKEDITOR.ALT,"Alt-"]],d="",e=0;e<c.length;e++)a&c[e][0]&&(a-=c[e][0],d+=c[e][1]);return CodeMirror.keyNames[a]?d+CodeMirror.keyNames[a]:null}var d=a.ui.space("contents").getDocument().createElement("textarea");d.setStyles(CKEDITOR.tools.extend({width:CKEDITOR.env.ie7Compat?"99%":"100%",height:"100%",resize:"none",outline:"none","text-align":"left"},CKEDITOR.tools.cssVendorPrefix("tab-size",
a.config.sourceAreaTabSize||4)));var f=[a.lang.editor,a.name].join();d.setAttributes({dir:"ltr",tabIndex:CKEDITOR.env.webkit?-1:a.tabIndex,role:"textbox","aria-label":f});d.addClass("cke_source");d.addClass("cke_reset");d.addClass("cke_enable_context_menu");a.ui.space("contents").append(d);window["editable_"+a.id]=a.editable(new e(a,d));window["editable_"+a.id].setData(a.getData(1));window["editable_"+a.id].editorID=a.id;a.fire("ariaWidget",this);d=window["editable_"+a.id];f=d.getParent();c.lineNumbers&&
c.enableCodeFolding&&(window["foldFunc_"+a.id]=CodeMirror.newFoldFunction(CodeMirror.tagRangeFinder));var h={"Ctrl-Q":function(b){if(c.enableCodeFolding)window["foldFunc_"+a.id](b,b.getCursor().line)}};(function(c){var g=a.config.keystrokes;if(CKEDITOR.tools.isArray(g))for(var d=0;d<g.length;d++){var e=b(g[d][0]);null!==e&&function(b){c[e]=function(){a.execCommand(b)}}(g[d][1])}})(h);window["codemirror_"+a.id]=CodeMirror.fromTextArea(d.$,{mode:c.mode,matchBrackets:c.matchBrackets,matchTags:c.matchTags,
workDelay:300,workTime:35,readOnly:a.readOnly,lineNumbers:c.lineNumbers,lineWrapping:!0,autoCloseTags:c.autoCloseTags,autoCloseBrackets:c.autoCloseBrackets,highlightSelectionMatches:c.highlightMatches,continueComments:c.continueComments,indentWithTabs:c.indentWithTabs,theme:c.theme,showTrailingSpace:c.showTrailingSpace,showCursorWhenSelecting:!0,styleActiveLine:c.styleActiveLine,extraKeys:h,foldGutter:!0,gutters:["CodeMirror-linenumbers","CodeMirror-foldgutter"]});d=0==f.$.clientHeight?a.ui.space("contents").getStyle("height"):
f.$.clientHeight+"px";window["codemirror_"+a.id].config=c;c.autoFormatOnStart&&(c.useBeautify?(f=window["codemirror_"+a.id].getValue(),window["codemirror_"+a.id].setValue(html_beautify(f,4," ",120,"collapse"))):window["codemirror_"+a.id].autoFormatAll({line:0,ch:0},{line:window["codemirror_"+a.id].lineCount(),ch:0}));window["codemirror_"+a.id].on("change",function(){window["codemirror_"+a.id].save();a.fire("change",this)});window["codemirror_"+a.id].setSize(null,d);if(c.lineNumbers&&c.enableCodeFolding)window["codemirror_"+
a.id].on("gutterClick",window["foldFunc_"+a.id]);if("function"===typeof c.onLoad)c.onLoad(window["codemirror_"+a.id],a);window["codemirror_"+a.id].on("blur",function(){a.fire("blur",this)});window["codemirror_"+a.id].on("keypress",function(b,g){if(c.enableCodeFormatting){var d=window["codemirror_"+a.id].getCursor(!0),e=window["codemirror_"+a.id].getCursor(!1);"keydown"!==g.type||!g.ctrlKey||75!==g.keyCode||g.shiftKey||g.altKey?"keydown"===g.type&&g.ctrlKey&&75===g.keyCode&&g.shiftKey&&!g.altKey?(window["codemirror_"+
a.id].commentRange(!1,d,e),c.autoFormatOnUncomment&&window["codemirror_"+a.id].autoFormatRange(d,e)):"keydown"===g.type&&g.ctrlKey&&75===g.keyCode&&!g.shiftKey&&g.altKey&&window["codemirror_"+a.id].autoFormatRange(d,e):window["codemirror_"+a.id].commentRange(!0,d,e)}})}var d=this.path,c=CKEDITOR.tools.extend({autoCloseBrackets:!0,autoCloseTags:!0,autoFormatOnStart:!1,autoFormatOnUncomment:!0,continueComments:!0,enableCodeFolding:!0,enableCodeFormatting:!0,enableSearchTools:!0,highlightMatches:!0,
indentWithTabs:!1,lineNumbers:!0,lineWrapping:!0,mode:"htmlmixed",matchBrackets:!0,matchTags:!0,showAutoCompleteButton:!0,showCommentButton:!0,showFormatButton:!0,showSearchButton:!0,showTrailingSpace:!0,showUncommentButton:!0,styleActiveLine:!0,theme:"default",useBeautify:!1},b.config.codemirror||{},!0),l=b.lang.codemirror;b.config.codemirror_theme&&(c.theme=b.config.codemirror_theme);b.config.codemirror_autoFormatOnStart&&(c.autoFormatOnStart=b.config.codemirror_autoFormatOnStart);b.plugins.bbcode&&
0>=c.mode.indexOf("bbcode")&&(c.mode="bbcode");(b.elementMode===CKEDITOR.ELEMENT_MODE_INLINE||b.plugins.sourcedialog)&&CKEDITOR.dialog.add("sourcedialog",function(a){function b(a,d){window["codemirror_"+a.id]=CodeMirror.fromTextArea(d,{mode:c.mode,matchBrackets:c.matchBrackets,matchTags:c.matchTags,workDelay:300,workTime:35,readOnly:a.readOnly,lineNumbers:c.lineNumbers,lineWrapping:c.lineWrapping,autoCloseTags:c.autoCloseTags,autoCloseBrackets:c.autoCloseBrackets,highlightSelectionMatches:c.highlightMatches,
continueComments:c.continueComments,indentWithTabs:c.indentWithTabs,theme:c.theme,showTrailingSpace:c.showTrailingSpace,showCursorWhenSelecting:!0,styleActiveLine:c.styleActiveLine,viewportMargin:Infinity,extraKeys:{"Ctrl-Q":function(b){if(c.enableCodeFolding)window["foldFunc_"+a.id](b,b.getCursor().line)}},foldGutter:!0,gutters:["CodeMirror-linenumbers","CodeMirror-foldgutter"]});var e=k+"px",f=h+"px";window["codemirror_"+a.id].config=c;if(c.autoFormatOnStart)if(c.useBeautify){var n=window["codemirror_"+
a.id].getValue();window["codemirror_"+a.id].setValue(html_beautify(n,4," ",120,"collapse"))}else window["codemirror_"+a.id].autoFormatAll({line:0,ch:0},{line:window["codemirror_"+a.id].lineCount(),ch:0});window["codemirror_"+a.id].on("change",function(){window["codemirror_"+a.id].save();a.fire("change",this)});window["codemirror_"+a.id].setSize(f,e);if(c.lineNumbers&&c.enableCodeFolding)window["codemirror_"+a.id].on("gutterClick",window["foldFunc_"+a.id]);if("function"===typeof c.onLoad)c.onLoad(window["codemirror_"+
a.id],a);window["codemirror_"+a.id].on("blur",function(){a.fire("blur",this)});window["codemirror_"+a.id].on("keypress",function(b,d){if(c.enableCodeFormatting){var e=window["codemirror_"+a.id].getCursor(!0),f=window["codemirror_"+a.id].getCursor(!1);"keydown"!==d.type||!d.ctrlKey||75!==d.keyCode||d.shiftKey||d.altKey?"keydown"===d.type&&d.ctrlKey&&75===d.keyCode&&d.shiftKey&&!d.altKey?(window["codemirror_"+a.id].commentRange(!1,e,f),c.autoFormatOnUncomment&&window["codemirror_"+a.id].autoFormatRange(e,
f)):"keydown"===d.type&&d.ctrlKey&&75===d.keyCode&&!d.shiftKey&&d.altKey&&window["codemirror_"+a.id].autoFormatRange(e,f):window["codemirror_"+a.id].commentRange(!0,e,f)}})}var e=CKEDITOR.document.getWindow().getViewPaneSize(),h=Math.min(e.width-70,800),k=e.height/1.5,m;return{title:a.lang.sourcedialog.title,minWidth:h,minHeight:k,resizable:CKEDITOR.DIALOG_RESIZE_NONE,onShow:function(){this.getContentElement("main","data").focus();this.getContentElement("main","AutoComplete").setValue(c.autoCloseTags,
!0);var e=this.getContentElement("main","data").getInputElement().$;this.setValueOf("main","data",m=a.getData());IsStyleSheetAlreadyLoaded(d+"css/codemirror.min.css")||CKEDITOR.document.appendStyleSheet(d+"css/codemirror.min.css");c.theme.length&&"default"!=c.theme&&!IsStyleSheetAlreadyLoaded(d+"theme/"+c.theme+".css")&&CKEDITOR.document.appendStyleSheet(d+"theme/"+c.theme+".css");"undefined"==typeof CodeMirror?CKEDITOR.scriptLoader.load(d+"js/codemirror.min.js",function(){CKEDITOR.scriptLoader.load(f(),
function(){b(a,e)})}):CodeMirror.prototype.autoFormatAll?b(a,e):CKEDITOR.scriptLoader.load(f(),function(){b(a,e)})},onCancel:function(b){b.data.hide&&(window["codemirror_"+a.id].toTextArea(),window["codemirror_"+a.id]=null)},onOk:function(){function b(c){var d=this;a.setData(c,function(){d.hide();var b=a.createRange();b.moveToElementEditStart(a.editable());b.select()})}return function(){window["codemirror_"+a.id].toTextArea();window["codemirror_"+a.id]=null;var c=this.getValueOf("main","data").replace(/\r/g,
"");if(c===m)return!0;CKEDITOR.env.ie?CKEDITOR.tools.setTimeout(b,0,this,c):b.call(this,c);return!1}}(),contents:[{id:"main",label:a.lang.sourcedialog.title,elements:[{type:"hbox",style:"width: 80px;margin:0;",widths:["20px","20px","20px","20px"],children:[{type:"button",id:"searchCode",label:"",title:l.searchCode,"class":"searchCodeButton",onClick:function(){CodeMirror.commands.find(window["codemirror_"+a.id])}},{type:"button",id:"autoFormat",label:"",title:l.autoFormat,"class":"autoFormat",onClick:function(){var b=
window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].autoFormatRange(b,c)}},{type:"button",id:"CommentSelectedRange",label:"",title:l.commentSelectedRange,"class":"CommentSelectedRange",onClick:function(){var b=window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].commentRange(!0,b,c)}},{type:"button",id:"UncommentSelectedRange",label:"",title:l.uncommentSelectedRange,"class":"UncommentSelectedRange",
onClick:function(){var b=window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].commentRange(!1,b,c);window["codemirror_"+a.id].config.autoFormatOnUncomment&&window["codemirror_"+a.id].autoFormatRange(b,c)}}]},{type:"checkbox",id:"AutoComplete",label:l.autoCompleteToggle,title:l.autoCompleteToggle,onChange:function(){window["codemirror_"+a.id].setOption("autoCloseTags",this.getValue())}},{type:"textarea",id:"data",dir:"ltr",inputStyle:"cursor:auto;width:"+
h+"px;height:"+k+"px;tab-size:4;text-align:left;","class":"cke_source cke_enable_context_menu"}]}]}});b.commands.find&&(b.commands.find.modes={wysiwyg:1,source:1},b.commands.find.exec=function(){"wysiwyg"===b.mode?b.openDialog("find"):CodeMirror.commands.find(window["codemirror_"+b.id])});b.commands.replace&&(b.commands.replace.modes={wysiwyg:1,source:1},b.commands.replace.exec=function(){"wysiwyg"===b.mode?b.openDialog("replace"):CodeMirror.commands.replace(window["codemirror_"+b.id])});var k=CKEDITOR.plugins.sourcearea;
k.commands.searchCode||(CKEDITOR.plugins.sourcearea.commands={source:{modes:{wysiwyg:1,source:1},editorFocus:!1,readOnly:1,exec:function(a){"wysiwyg"===a.mode&&a.fire("saveSnapshot");a.getCommand("source").setState(CKEDITOR.TRISTATE_DISABLED);a.setMode("source"===a.mode?"wysiwyg":"source")},canUndo:!1},searchCode:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(a){CodeMirror.commands.find(window["codemirror_"+a.id])},canUndo:!0},autoFormat:{modes:{wysiwyg:0,source:1},editorFocus:!1,
readOnly:1,exec:function(a){var b=window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].autoFormatRange(b,c)},canUndo:!0},commentSelectedRange:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(a){var b=window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].commentRange(!0,b,c)},canUndo:!0},uncommentSelectedRange:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(a){var b=
window["codemirror_"+a.id].getCursor(!0),c=window["codemirror_"+a.id].getCursor(!1);window["codemirror_"+a.id].commentRange(!1,b,c);window["codemirror_"+a.id].config.autoFormatOnUncomment&&window["codemirror_"+a.id].autoFormatRange(b,c)},canUndo:!0},autoCompleteToggle:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(a){this.state==CKEDITOR.TRISTATE_ON?window["codemirror_"+a.id].setOption("autoCloseTags",!1):this.state==CKEDITOR.TRISTATE_OFF&&window["codemirror_"+a.id].setOption("autoCloseTags",
!0);this.toggleState()},canUndo:!0}});b.addMode("source",function(a){IsStyleSheetAlreadyLoaded(d+"css/codemirror.min.css")||CKEDITOR.document.appendStyleSheet(d+"css/codemirror.min.css");c.theme.length&&"default"!=c.theme&&!IsStyleSheetAlreadyLoaded(d+"theme/"+c.theme+".css")&&CKEDITOR.document.appendStyleSheet(d+"theme/"+c.theme+".css");"undefined"==typeof CodeMirror?CKEDITOR.scriptLoader.load(d+"js/codemirror.min.js",function(){CKEDITOR.scriptLoader.load(f(),function(){h(b);a()})}):CodeMirror.prototype.autoFormatAll?
(h(b),a()):CKEDITOR.scriptLoader.load(f(),function(){h(b);a()})});b.addCommand("source",k.commands.source);b.ui.addButton&&b.ui.addButton("Source",{label:b.lang.codemirror.toolbar,command:"source",toolbar:"mode,10"});c.enableCodeFormatting&&(b.addCommand("searchCode",k.commands.searchCode),b.addCommand("autoFormat",k.commands.autoFormat),b.addCommand("commentSelectedRange",k.commands.commentSelectedRange),b.addCommand("uncommentSelectedRange",k.commands.uncommentSelectedRange),b.addCommand("autoCompleteToggle",
k.commands.autoCompleteToggle),b.ui.addButton&&((c.showFormatButton||c.showCommentButton||c.showUncommentButton||c.showSearchButton)&&b.ui.add("-",CKEDITOR.UI_SEPARATOR,{toolbar:"mode,30"}),c.showFormatButton&&b.ui.addButton("autoFormat",{label:l.autoFormat,command:"autoFormat",toolbar:"mode,50"}),c.showCommentButton&&b.ui.addButton("CommentSelectedRange",{label:l.commentSelectedRange,command:"commentSelectedRange",toolbar:"mode,60"}),c.showUncommentButton&&b.ui.addButton("UncommentSelectedRange",
{label:l.uncommentSelectedRange,command:"uncommentSelectedRange",toolbar:"mode,70"}),c.showAutoCompleteButton&&b.ui.addButton("AutoComplete",{label:l.autoCompleteToggle,command:"autoCompleteToggle",toolbar:"mode,80"})));b.on("beforeModeUnload",function(a){if("source"===b.mode&&b.plugins.textselection){var c=b.getTextSelection();c.startOffset=LineChannelToOffSet(window["codemirror_"+b.id],window["codemirror_"+b.id].getCursor(!0));c.endOffset=LineChannelToOffSet(window["codemirror_"+b.id],window["codemirror_"+
b.id].getCursor(!1));delete c.element;c.createBookmark(b);sourceBookmark=!0;b.undoManager&&b.undoManager.unlock();a.data=c.content}});b.on("mode",function(){b.getCommand("source").setState("source"===b.mode?CKEDITOR.TRISTATE_ON:CKEDITOR.TRISTATE_OFF);if("source"===b.mode&&(b.getCommand("autoCompleteToggle").setState(window["codemirror_"+b.id].config.autoCloseTags?CKEDITOR.TRISTATE_ON:CKEDITOR.TRISTATE_OFF),b.plugins.textselection&&textRange)){var a,c;a=OffSetToLineChannel(window["codemirror_"+b.id],
textRange.startOffset);"undefined"==typeof textRange.endOffset?(window["codemirror_"+b.id].focus(),window["codemirror_"+b.id].setCursor(a)):(window["codemirror_"+b.id].focus(),c=OffSetToLineChannel(window["codemirror_"+b.id],textRange.endOffset),window["codemirror_"+b.id].setSelection(a,c))}});b.on("resize",function(){if(window["editable_"+b.id]&&"source"===b.mode){var a=window["editable_"+b.id].getParent();window["codemirror_"+b.id].setSize(a.$.clientWidth+"px",a.$.clientHeight+"px")}});b.on("readOnly",
function(){window["editable_"+b.id]&&"source"===b.mode&&window["codemirror_"+b.id].setOption("readOnly",this.readOnly)});b.on("instanceReady",function(a){b.container.getPrivate().events.contextmenu.listeners.splice(0,1);a=b.commands.selectAll;null!=a&&(a.exec=function(){if("source"===b.mode)window["codemirror_"+b.id].setSelection({line:0,ch:0},{line:window["codemirror_"+b.id].lineCount(),ch:0});else{var a=b.editable();if(a.is("body"))b.document.$.execCommand("SelectAll",!1,null);else{var c=b.createRange();
c.selectNodeContents(a);c.select()}b.forceNextSelectionCheck();b.selectionChange()}})});if("undefined"!=typeof jQuery&&jQuery('a[data-toggle\x3d"tab"]')&&window["codemirror_"+b.id])jQuery('a[data-toggle\x3d"tab"]').on("shown.bs.tab",function(){window["codemirror_"+b.id].refresh()});b.on("setData",function(a){window["editable_"+a.editor.id]&&"source"===a.editor.mode&&window["codemirror_"+a.editor.id].setValue(a.data.dataValue)})}});var e=CKEDITOR.tools.createClass({base:CKEDITOR.editable,proto:{setData:function(b){this.setValue(b);
window["editable_"+this.editor.id]&&"source"===this.editor.mode&&window["codemirror_"+this.editor.id].setValue(b);this.editor.fire("dataReady")},getData:function(){return this.getValue()},insertHtml:function(){},insertElement:function(){},insertText:function(){},setReadOnly:function(b){this[(b?"set":"remove")+"Attribute"]("readOnly","readonly")},editorID:null,detach:function(){window["codemirror_"+this.editorID].toTextArea();window["editable_"+this.editorID]=null;window["codemirror_"+this.editorID]=
null;e.baseProto.detach.call(this);this.clearCustomData();this.remove()}}})})();
CKEDITOR.plugins.sourcearea={commands:{source:{modes:{wysiwyg:1,source:1},editorFocus:!1,readOnly:1,exec:function(e){"wysiwyg"===e.mode&&e.fire("saveSnapshot");e.getCommand("source").setState(CKEDITOR.TRISTATE_DISABLED);e.setMode("source"===e.mode?"wysiwyg":"source")},canUndo:!1},searchCode:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(e){CodeMirror.commands.find(window["codemirror_"+e.id])},canUndo:!0},autoFormat:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:0,exec:function(e){var b=
window["codemirror_"+e.id].getCursor(!0),f=window["codemirror_"+e.id].getCursor(!1);window["codemirror_"+e.id].autoFormatRange(b,f)},canUndo:!0},commentSelectedRange:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:0,exec:function(e){var b=window["codemirror_"+e.id].getCursor(!0),f=window["codemirror_"+e.id].getCursor(!1);window["codemirror_"+e.id].commentRange(!0,b,f)},canUndo:!0},uncommentSelectedRange:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:0,exec:function(e){var b=window["codemirror_"+
e.id].getCursor(!0),f=window["codemirror_"+e.id].getCursor(!1);window["codemirror_"+e.id].commentRange(!1,b,f);window["codemirror_"+e.id].config.autoFormatOnUncomment&&window["codemirror_"+e.id].autoFormatRange(b,f)},canUndo:!0},autoCompleteToggle:{modes:{wysiwyg:0,source:1},editorFocus:!1,readOnly:1,exec:function(e){this.state==CKEDITOR.TRISTATE_ON?window["codemirror_"+e.id].setOption("autoCloseTags",!1):this.state==CKEDITOR.TRISTATE_OFF&&window["codemirror_"+e.id].setOption("autoCloseTags",!0);
this.toggleState()},canUndo:!0}}};function LineChannelToOffSet(e,b){var f=b.line,h=f+b.ch;for(i=0;i<f;i++)h+=e.getLine(i).length;return h}function OffSetToLineChannel(e,b){var f=0,h=0,d=0;for(i=0;i<e.lineCount();i++){len=e.getLine(i).length;if(b<d+len){f=i;h=b-d;break}len++;d+=len}return{line:f,ch:h}}function IsStyleSheetAlreadyLoaded(e){for(var b=CKEDITOR.document.getHead().find("link"),f=0;f<b.count();f++)if(b.getItem(f).$.href===e)return!0;return!1};
