/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.addTemplates("default",{imagesPath:CKEDITOR.getUrl(CKEDITOR.plugins.getPath("templates")+"templates/images/"),templates:[{title:"Kolm tulpa. Keskel üks suur.",image:"template1.gif",description:"Kolm tulpa. Keskmine suur.",html:'\x3cdiv class\x3d"wrap-template-new"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-md-3"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-6"\x3e\x3cdiv class\x3d"wiki-template-box box-content"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e \x3cdiv class\x3d"col-md-3"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e  \x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e\x3c/div\x3e'},
{title:"Kaks tulpa. Paremal üks suur.",image:"template2.gif",description:"Kaks tulpa. Paremal üks suur.",html:'\x3cdiv class\x3d"wrap-template-new"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-md-3"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-9"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e\x3c/div\x3e'},
{title:"Kaks tulpa. Vasakul üks suur.",image:"template3.gif",description:"Kaks tulpa. Vasakul üks suur.",html:'\x3cdiv class\x3d"wrap-template-new"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-md-9"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-3"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e\x3c/div\x3e'},
{title:"Kaks tulpa",image:"template4.gif",description:"Kaks tulpa.",html:'\x3cdiv class\x3d"wrap-template-new"\x3e\x3cdiv class\x3d"row"\x3e\x3cdiv class\x3d"col-md-6"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"col-md-6"\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e \x3c/div\x3e\x3c/div\x3e'},
{title:"Üksik div",image:"template5.gif",description:"Üksik div",html:'\x3cdiv class\x3d"wiki-template-box"\x3e\x3cdiv\x3e\x3c/div\x3e\x3c/div\x3e'}]});
